const ACTION_TYPES = {
  GET_USERS_COORDINATES: 'GET_USERS_COORDINATES',
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_LOGIN: "GET_LOGIN",
  FETCH_ALL_POSTS: "FETCH_ALL_POSTS",
  POST_PAYMENT: "POST_PAYMENT",
  FETCH_CHECKOUTS_DETAILS: "FETCH_CHECKOUTS_DETAILS",
  GET_FILTERED: "GET_FILTERED",
  GET_SEARCH: "GET_SEARCH",
  GET_LOGOUT: "GET_LOGOUT",
  REGISTER_LOGIN: "REGISTER_LOGIN",
  FILL_LOGIN: "FILL_LOGIN",
  GET_ADMIN_ALL: "GET_ADMIN_ALL",
  GET_LOGIN_FORGOT: "GET_LOGIN_FORGOT",
};
export default ACTION_TYPES;
