const ACTION_TYPES = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_LOGIN: "GET_LOGIN",
  FETCH_ALL_POSTS: "FETCH_ALL_POSTS",
  POST_PAYMENT: "POST_PAYMENT",
  FETCH_CHECKOUTS_DETAILS: "FETCH_CHECKOUTS_DETAILS"
};
export default ACTION_TYPES;
